USE master;
IF DB_ID('TemporalDb') IS NOT NULL
BEGIN
    ALTER DATABASE TemporalDb SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE TemporalDb;
END;
GO

CREATE DATABASE TemporalDb;
GO
ALTER DATABASE TemporalDb
ADD FILEGROUP fgmo
CONTAINS MEMORY_OPTIMIZED_DATA;
GO
ALTER DATABASE [TemporalDb]
ADD FILE
    (
        NAME = N'mof',
        FILENAME = N'/var/opt/mssql/data/mof'
    )
TO FILEGROUP [fgmo];
GO
ALTER DATABASE TemporalDb SET RECOVERY SIMPLE;
