USE sandbox;
DECLARE @cnt INT;
SET NOCOUNT OFF;
	IF @@TRANCOUNT>0
		ROLLBACK;
WAITFOR DELAY '00:00:01';
WHILE 1=1
BEGIN;
	BEGIN TRAN;
	SELECT @cnt = COUNT(*) FROM dbo.tbl WITH(HOLDLOCK);
	RAISERROR('Count: %d',10,1,@cnt) WITH NOWAIT;
	WAITFOR DELAY '00:00:05';
	COMMIT;
END; 
ROLLBACK